# Конфигурация lasplot

# Адрес и порт сервера
bind_address = "127.0.0.1"
bind_port = 8088

# Папка с LAS файлами (если указано имя файла без URL)
samples_dir = "samples"

# Файл со списком LAS файлов для тестовой страницы
#laslist_file = "/home/shestero/lasplot/ks_las_files.txt" # "laslist.txt"

# Количество шагов основного параметра на одну строку HTML таблицы
html_row_steps = 25

# Количество пикселей в высоту на один шаг
pixels_per_step = 6

# Ширина изображений в пикселях
image_width = 1000

# Расстояние по высоте между горизонтальными шкалами в пикселях
scale_spacing = 20

# Максимальное количество кривых для отображения в шкале
max_scales = 6

# Размеры засечек на шкалах (в пикселях)
tick_size_major = 8
tick_size_minor = 4

# Палитра цветов по умолчанию (шестизначные hex)
default_colors = [
    "FF0000",  # красный
    "0000FF",  # синий
    "00FF00",  # зеленый
    "FF00FF",  # пурпурный
    "00FFFF",  # голубой
    "FFA500",  # оранжевый
    "800080",  # фиолетовый
    "FF8080",
    "802080",
    "804090",
    "8060A0",
    "8080B0",
    "80A0C0",
    "80C0D0",
    "80F0E0",
]

# Показывать значение основного параметра в отдельной колонке (true) или наложить на картинку (false)
separate_depth_column = false

